name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: [ "main" ] # Cambia esto a "master" si esa es tu rama principal

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto (Build)
        run: npm run build

      - name: Copiar index.html a 404.html
        run: cp dist/index.html dist/404.html

      - name: Verificar archivos construidos
        run: ls -la dist

      - name: Subir artefacto (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Aquí le decimos que solo tome la carpeta compilada

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4